@startuml

title Population Dynamics Model

start
repeat
    :Parâmetros e condições iniciais;
    repeat
    
    Switch (Hosts->Sorteia um valor)
    case(valor pertence ao 1º intervalo)
        :Hosts ++;
    case (valor pertence ao 2º intervalo)
        :Hosts --;
    case (valor pertence ao 3º intervalo)
        :Hosts --;
    endswitch

    Switch (Infected->Sorteia um valor)
    case (valor pertence ao 1º intervalo)
        :Infected ++;
    case (valor pertence ao 2º intervalo)
        :Infected --;
    case (valor pertence ao 3º intervalo)
        :Infected --;
    endswitch

    Switch (Parasitoid->Sorteia um valor)
    case (valor pertence ao 1º intervalo)
        :Parasitoid ++;
    case (valor pertence ao 2º intervalo)
        :Parasitoid --;
    endswitch

    :Atualização do # de indivíduos;
    :Guarda informações do dia;
    repeat while (Próximo passo de tempo)
repeat while (Finalizou o # de evoluções?)

:Cálculo da média e análise gráfica; 

stop

@enduml