version: "3.8"

services:
  equilibrium_first:
    image: alexandrendev/rafikov-avg:1.0.0
    environment:
      #MUDE OS VALORES DEPOIS DO = CONFORME DESEJADO
      - EQUILIBRIUM=FIRST
      - DAYS=250
      - SIMULATIONS=100
    volumes:
      - ~/graphs:/app/graphs
    container_name: norm_equilibrium_first
    restart: on-failure

  equilibrium_second:
    image: alexandrendev/rafikov-avg:1.0.0
    environment:
    #MUDE OS VALORES DEPOIS DO = CONFORME DESEJADO
      - EQUILIBRIUM=SECOND
      - DAYS=250
      - SIMULATIONS=100
    volumes:
      - ~/graphs:/app/graphs
    container_name: norm_equilibrium_second
    restart: on-failure

  equilibrium_third:
    image: alexandrendev/rafikov-avg:1.0.0
    environment:
    #MUDE OS VALORES DEPOIS DO = CONFORME DESEJADO
      - EQUILIBRIUM=THIRD
      - DAYS=250
      - SIMULATIONS=100
    volumes:
      - ~/graphs:/app/graphs
    container_name: norm_equilibrium_third
    restart: on-failure

    #docker-compose build --no-cache