version: "3.8"

services:
  equilibrium_first:
    image: teste:latest  # Nome da imagem já buildada
    environment:
      - EQUILIBRIUM=FIRST
    volumes:
      - ~/graphs:/app/graphs  # Mapeia o diretório local ./graphs para /app/graphs dentro do container
    container_name: equilibrium_first
    restart: on-failure

  equilibrium_second:
    image: teste:latest  # Nome da imagem já buildada
    environment:
      - EQUILIBRIUM=SECOND
    volumes:
      - ~/graphs:/app/graphs  # Mapeia o diretório local ./graphs para /app/graphs dentro do container
    container_name: equilibrium_second
    restart: on-failure

  equilibrium_third:
    image: teste:latest  # Nome da imagem já buildada
    environment:
      - EQUILIBRIUM=THIRD
    volumes:
      - ~/graphs:/app/graphs  # Mapeia o diretório local ./graphs para /app/graphs dentro do container
    container_name: equilibrium_third
    restart: on-failure


